name: Testing API
on: [push, pull_request] #Events that trigger the workflow
jobs: 
  testing-api: #Job name
    runs-on: ubuntu-latest
    env: #Setting environment variables
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }} #Accesing secrets variables stored in github
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2 #This is an action that already exists in Github. It will basically pull the repository
      - name: Creating and activting vritualenv
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
      - name: Installing dependencies
        run: |
          pip install dvc[gs]
          pip install -r requirements_test.txt
      - name: Test API # setter.py has the credentials
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          dvc pull model/model.pkl -r model-tracker

